import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Fujifilm Instax Mini 11 Instant Camera",
    price: "3500.00",
    color: "Black and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Remote Control 3D Famous car With 3D lights",
    price: "25.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "New Classy LED Watch ( BLACK) For MEN",
    price: "2200.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

// export const paginationItems = [
//   {
//     _id: 1001,
//     img: "https://fujifilm-x.com/products-cameras-static/gfx100/assets/images/top/common/kv_camera.png",
//     productName: "FUJIFILM GFX 50R",
//     price: "3500.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1002,
//     img: "https://static-01.daraz.lk/p/613c77ebe23bd8a50ae07880bcd010a2.jpg",
//     productName: "New Classy LED Watch ( BLACK) For MEN",
//     price: "1800.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1003,
//     img: spfThree,
//     productName: "Headphones",
//     price: "850.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1004,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1005,
//     img: bestSellerOne,
//     productName: "Iphone",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1006,
//     img: bestSellerTwo,
//     productName: "Item2",
//     price: "180.00",
//     color: "Gray",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1007,
//     img: "https://www.boat-lifestyle.com/cdn/shop/products/c2386af9-4349-432f-8ba5-2b6aa06025c8_76178e65-cec1-436c-87e2-f834b18ffd42_600x.png?v=1658824214",
//     productName: "Air pro ear buds",
//     price: "250.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1008,
//     img: "https://uk.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw6648a0d0/1.JBL_TUNE_230NC_Product%20image_Hero_Black.png?sw=680&sh=680", //bestSellerFour
//     productName: "Speaker",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1009,
//     img: "https://m.media-amazon.com/images/I/61kSiIi2SKL._AC_UF1000,1000_QL80_.jpg",
//     productName: "Metal Car",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1010,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1011,
//     img: "https://5.imimg.com/data5/SELLER/Default/2023/3/294007039/BE/SH/ZG/157647903/71l5lns6rql-sy450-1--500x500.jpg",
//     productName: "Jeep",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1012,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1013,
//     img: newArrTwo,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },

//   {
//     _id: 1014,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1015,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1016,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1017,
//     img: "https://images.meesho.com/images/products/97256828/gzq7j_512.webp",
//     productName: "Car Toy",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1018,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1019,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1020,
//     img: newArrThree,
//     productName: "cloth Basket",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1021,
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1022,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1023,
//     img: bestSellerOne,
//     productName: "Flower Base",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1024,
//     img: spfOne,
//     productName: "Cap for Boys",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1025,
//     img: spfTwo,
//     productName: "Marshall Speaker",
//     price: "1180.00",
//     color: "Gray",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1026,
//     img: spfThree,
//     productName: "Headphones",
//     price: "625.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1027,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1028,
//     img: bestSellerOne,
//     productName: "Highcom CCTV",
//     price: "835.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1029,
//     img: bestSellerTwo,
//     productName: "Apple Ear Buds pro 2",
//     price: "480.00",
//     color: "Gray",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1030,
//     img: bestSellerThree,
//     productName: "Iphone 11",
//     price: "1025.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1031,
//     img: bestSellerFour,
//     productName: "Apple TV",
//     price: "2220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1032,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1033,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1034,
//     img: newArrThree,
//     productName: "I Pad pro 19",
//     price: "2080.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1035,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1036,
//     img: newArrTwo,
//     productName: "Smart Watch Rolex",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1037,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1038,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1039,
//     img: bestSellerFour,
//     productName: "JBL Ear Buds",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1040,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1041,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1042,
//     img: newArrThree,
//     productName: "IPad pro 20",
//     price: "1280.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1043,
//     img: spfThree,
//     productName: "Headphones",
//     price: "525.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1044,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "120.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1045,
//     img: bestSellerOne,
//     productName: "Lorex CCTV",
//     price: "1135.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1046,
//     img: spfOne,
//     productName: "AirPod Pro",
//     price: "1135.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
// ];
// =================== PaginationItems End here =================
